name: run Yad2search

on:
  schedule:
    - cron: '*/15 6-21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: read unique_date_added.json
        run: cat unique_date_added.json

      - name: run main.py
        run: python main.py

      - name: Commit and push  
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add unique_date_added.json  # or git add -A to add all files
          git commit -m "Updated unique_date_added.json"  # change this message if you want
          git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main || exit 0
